#pragma config(Sensor, dgtl1,  leftMotorEncoder, sensorRotation)
#pragma config(Sensor, dgtl2,  rightMotorEncoder, sensorRotation)
#pragma config(Motor,  port1,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftArm1,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftArm2,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightArm2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           rightArm1,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          frontRightMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward();
void brake();
void setAllMotors(int num);

task main()
{
	SensorValue[leftMotorEncoder] = 0;
	SensorValue[rightMotorEncoder] = 0;
	while (SensorValue[leftMotorEncoder] < 3600) {
		forward();
	}
	brake();


}
void forward() {
	setAllMotors(127);
}

void brake() {
	setAllMotors(0);
}

void setAllMotors(int num) {
	motor[backLeftMotor] = num;
	motor[frontLeftMotor] = num;
	motor[backRightMotor] = num;
	motor[frontRightMotor] = num;
}
