#pragma config(Sensor, dgtl1,  leftMotorEncoder, sensorRotation)
#pragma config(Sensor, dgtl2,  rightMotorEncoder, sensorRotation)
#pragma config(Sensor, dgtl3,  bottomLimitSwitch, sensorTouch)
#pragma config(Motor,  port1,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftArm1,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftArm2,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           conveyer,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightArm2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           rightArm1,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          frontRightMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.h"

#define DIRECTION 1 // 1 if blue, -1 if red
#define BUFFER_DISTANCE 3
#define MOTOR_POWER 100
#define KP 500

void locomoteAll(int power) {
	motor[frontLeftMotor] = power;
	motor[frontRightMotor] = power;
	motor[backLeftMotor] = power;
	motor[backRightMotor] = power;
}

void adjustSlaveMotor(int amount) {
	motor[backRightMotor] -= amount;
	motor[frontRightMotor] -= amount;
}

int motorStatus;
int goUntilGlob;
int leftEncoder;
int rightEncoder;
void moveStraight(float inches) {
	int startValue = SensorValue[leftMotorEncoder];
	int goUntil = 180 / 3.14 * (inches / WHEEL_RADIUS / WHEEL_TO_ENCODER_RATIO * WHEEL_FUDGE_FACTOR);
	goUntilGlob = goUntil;
	if (inches > 0) {
		locomoteAll(MOTOR_POWER);
	} else {
		locomoteAll(-MOTOR_POWER);
	}

	while (abs(SensorValue[leftMotorEncoder] - startValue) < abs(goUntil)) {
		motorStatus = SensorValue[leftMotorEncoder] - startValue;
		leftEncoder = SensorValue[leftMotorEncoder];
		rightEncoder = SensorValue[rightMotorEncoder];
		/*
			This code (c) 2013 some dudes on the internet
		*/
		int error = leftEncoder - rightEncoder;
		adjustSlaveMotor(error * KP);
		wait1Msec(10);
	}
	locomoteAll(0);
}


void turn(int degrees) {

}

void releaseTheFlag() {
	motor[conveyer] = -50;
	wait10Msec(30);
	motor[conveyer] = 0;
}
task main()
{
	moveStraight(50);


}
